package com.spfood.wos.workOrder.intf.domain;

import com.spfood.kernel.domain.DomainObject;
import java.util.Date;

public class Goods implements DomainObject {
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_goods.g_id
     *
     * @mbggenerated
     */
    private Long gId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_goods.goods_code
     *
     * @mbggenerated
     */
    private String goodsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_goods.gate_gory
     *
     * @mbggenerated
     */
    private String gateGory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_goods.goods_name
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_goods.goods_spec
     *
     * @mbggenerated
     */
    private String goodsSpec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_goods.unit
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_goods.pack_unit
     *
     * @mbggenerated
     */
    private String packUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_goods.total_sum
     *
     * @mbggenerated
     */
    private Float totalSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_goods.locked_sum
     *
     * @mbggenerated
     */
    private Float lockedSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_goods.can_sale_sum
     *
     * @mbggenerated
     */
    private Float canSaleSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_goods.total_min_sum
     *
     * @mbggenerated
     */
    private Float totalMinSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_goods.locked_min_sum
     *
     * @mbggenerated
     */
    private Float lockedMinSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_goods.can_sale_min_sum
     *
     * @mbggenerated
     */
    private Float canSaleMinSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_goods.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_goods.create_user_code
     *
     * @mbggenerated
     */
    private String createUserCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_goods.create_user_name
     *
     * @mbggenerated
     */
    private String createUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_goods.source
     *
     * @mbggenerated
     */
    private Integer source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_goods.comments
     *
     * @mbggenerated
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_goods.gate_gory_name
     *
     * @mbggenerated
     */
    private String gateGoryName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_goods.g_id
     *
     * @return the value of wms_goods.g_id
     *
     * @mbggenerated
     */
    public Long getgId() {
        return gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_goods.g_id
     *
     * @param gId the value for wms_goods.g_id
     *
     * @mbggenerated
     */
    public void setgId(Long gId) {
        this.gId = gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_goods.goods_code
     *
     * @return the value of wms_goods.goods_code
     *
     * @mbggenerated
     */
    public String getGoodsCode() {
        return goodsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_goods.goods_code
     *
     * @param goodsCode the value for wms_goods.goods_code
     *
     * @mbggenerated
     */
    public void setGoodsCode(String goodsCode) {
        this.goodsCode = goodsCode == null ? null : goodsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_goods.gate_gory
     *
     * @return the value of wms_goods.gate_gory
     *
     * @mbggenerated
     */
    public String getGateGory() {
        return gateGory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_goods.gate_gory
     *
     * @param gateGory the value for wms_goods.gate_gory
     *
     * @mbggenerated
     */
    public void setGateGory(String gateGory) {
        this.gateGory = gateGory == null ? null : gateGory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_goods.goods_name
     *
     * @return the value of wms_goods.goods_name
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_goods.goods_name
     *
     * @param goodsName the value for wms_goods.goods_name
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_goods.goods_spec
     *
     * @return the value of wms_goods.goods_spec
     *
     * @mbggenerated
     */
    public String getGoodsSpec() {
        return goodsSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_goods.goods_spec
     *
     * @param goodsSpec the value for wms_goods.goods_spec
     *
     * @mbggenerated
     */
    public void setGoodsSpec(String goodsSpec) {
        this.goodsSpec = goodsSpec == null ? null : goodsSpec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_goods.unit
     *
     * @return the value of wms_goods.unit
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_goods.unit
     *
     * @param unit the value for wms_goods.unit
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_goods.pack_unit
     *
     * @return the value of wms_goods.pack_unit
     *
     * @mbggenerated
     */
    public String getPackUnit() {
        return packUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_goods.pack_unit
     *
     * @param packUnit the value for wms_goods.pack_unit
     *
     * @mbggenerated
     */
    public void setPackUnit(String packUnit) {
        this.packUnit = packUnit == null ? null : packUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_goods.total_sum
     *
     * @return the value of wms_goods.total_sum
     *
     * @mbggenerated
     */
    public Float getTotalSum() {
        return totalSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_goods.total_sum
     *
     * @param totalSum the value for wms_goods.total_sum
     *
     * @mbggenerated
     */
    public void setTotalSum(Float totalSum) {
        this.totalSum = totalSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_goods.locked_sum
     *
     * @return the value of wms_goods.locked_sum
     *
     * @mbggenerated
     */
    public Float getLockedSum() {
        return lockedSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_goods.locked_sum
     *
     * @param lockedSum the value for wms_goods.locked_sum
     *
     * @mbggenerated
     */
    public void setLockedSum(Float lockedSum) {
        this.lockedSum = lockedSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_goods.can_sale_sum
     *
     * @return the value of wms_goods.can_sale_sum
     *
     * @mbggenerated
     */
    public Float getCanSaleSum() {
        return canSaleSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_goods.can_sale_sum
     *
     * @param canSaleSum the value for wms_goods.can_sale_sum
     *
     * @mbggenerated
     */
    public void setCanSaleSum(Float canSaleSum) {
        this.canSaleSum = canSaleSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_goods.total_min_sum
     *
     * @return the value of wms_goods.total_min_sum
     *
     * @mbggenerated
     */
    public Float getTotalMinSum() {
        return totalMinSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_goods.total_min_sum
     *
     * @param totalMinSum the value for wms_goods.total_min_sum
     *
     * @mbggenerated
     */
    public void setTotalMinSum(Float totalMinSum) {
        this.totalMinSum = totalMinSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_goods.locked_min_sum
     *
     * @return the value of wms_goods.locked_min_sum
     *
     * @mbggenerated
     */
    public Float getLockedMinSum() {
        return lockedMinSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_goods.locked_min_sum
     *
     * @param lockedMinSum the value for wms_goods.locked_min_sum
     *
     * @mbggenerated
     */
    public void setLockedMinSum(Float lockedMinSum) {
        this.lockedMinSum = lockedMinSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_goods.can_sale_min_sum
     *
     * @return the value of wms_goods.can_sale_min_sum
     *
     * @mbggenerated
     */
    public Float getCanSaleMinSum() {
        return canSaleMinSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_goods.can_sale_min_sum
     *
     * @param canSaleMinSum the value for wms_goods.can_sale_min_sum
     *
     * @mbggenerated
     */
    public void setCanSaleMinSum(Float canSaleMinSum) {
        this.canSaleMinSum = canSaleMinSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_goods.create_time
     *
     * @return the value of wms_goods.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_goods.create_time
     *
     * @param createTime the value for wms_goods.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_goods.create_user_code
     *
     * @return the value of wms_goods.create_user_code
     *
     * @mbggenerated
     */
    public String getCreateUserCode() {
        return createUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_goods.create_user_code
     *
     * @param createUserCode the value for wms_goods.create_user_code
     *
     * @mbggenerated
     */
    public void setCreateUserCode(String createUserCode) {
        this.createUserCode = createUserCode == null ? null : createUserCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_goods.create_user_name
     *
     * @return the value of wms_goods.create_user_name
     *
     * @mbggenerated
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_goods.create_user_name
     *
     * @param createUserName the value for wms_goods.create_user_name
     *
     * @mbggenerated
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_goods.source
     *
     * @return the value of wms_goods.source
     *
     * @mbggenerated
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_goods.source
     *
     * @param source the value for wms_goods.source
     *
     * @mbggenerated
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_goods.comments
     *
     * @return the value of wms_goods.comments
     *
     * @mbggenerated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_goods.comments
     *
     * @param comments the value for wms_goods.comments
     *
     * @mbggenerated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_goods.gate_gory_name
     *
     * @return the value of wms_goods.gate_gory_name
     *
     * @mbggenerated
     */
    public String getGateGoryName() {
        return gateGoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_goods.gate_gory_name
     *
     * @param gateGoryName the value for wms_goods.gate_gory_name
     *
     * @mbggenerated
     */
    public void setGateGoryName(String gateGoryName) {
        this.gateGoryName = gateGoryName == null ? null : gateGoryName.trim();
    }
}