package com.spfood.oms.cart.intf.domain;

import com.spfood.kernel.domain.DomainObject;

import java.math.BigDecimal;
import java.util.Date;

public class CartCommodity implements DomainObject {
	private static final long serialVersionUID = 1L;
    
    private String comCode;

    
    private Long ccId;

    
    private String cartCode;

    
    private String orderNo;

   
    private String comName;

    
    private String peoperties;

    
    private Integer amount;

   
    private BigDecimal price;

    
    private BigDecimal sum;

    
    private Integer status;

    
    private Date addTime;

    
    private Date lastTime;
    
    private String pictureUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_commidty.comments
     *
     * @mbggenerated
     */
    private String comments;

	public String getComCode() {
		return comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	public Long getCcId() {
		return ccId;
	}

	public void setCcId(Long ccId) {
		this.ccId = ccId;
	}

	public String getCartCode() {
		return cartCode;
	}

	public void setCartCode(String cartCode) {
		this.cartCode = cartCode;
	}

	public String getOrderNo() {
		return orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	public String getComName() {
		return comName;
	}

	public void setComName(String comName) {
		this.comName = comName;
	}

	public String getPeoperties() {
		return peoperties;
	}

	public void setPeoperties(String peoperties) {
		this.peoperties = peoperties;
	}

	public Integer getAmount() {
		return amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	public BigDecimal getPrice() {
		return price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public BigDecimal getSum() {
		return sum;
	}

	public void setSum(BigDecimal sum) {
		this.sum = sum;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getAddTime() {
		return addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	public Date getLastTime() {
		return lastTime;
	}

	public void setLastTime(Date lastTime) {
		this.lastTime = lastTime;
	}

	public String getComments() {
		return comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getPictureUrl() {
		return pictureUrl;
	}

	public void setPictureUrl(String pictureUrl) {
		this.pictureUrl = pictureUrl;
	}
	

    
}